# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rack", "~> 2.2"
gem "puma", "~> 5.3"

gem "statsd-ruby", "~> 1.5"
