---
- hosts: app_host
  remote_user: root
  tasks:
    - name: Run Server For Remote Benchmark
      shell:
        chdir: '/root/puma-performance-sketch/'
        cmd: make run
      environment:
        RACK_INSTURMENT: "{{ lookup('env', 'RACK_INSTURMENT') | default('true', true) }}"
        WRK_CONCURRENT: "{{ lookup('env', 'WRK_CONCURRENT') | default('4', true)  }}"
        PUMA_STATSD: "{{ lookup('env', 'PUMA_STATSD') | default('false', true) }}"
        PUMA_QUEUE_REQUESTS: "{{ lookup('env', 'PUMA_QUEUE_REQUESTS') | default('true', true) }}"
        DURATION: "{{ lookup('env', 'DURATION') | default('30', true)  }}"

      register: benchmark
      async: 1000
      poll: 0

    - name: Show benchmark output
      debug:
        msg: "{{ benchmark }}"

    - name: Kill Server
      shell:
        chdir: '/root/puma-performance-sketch/'
        cmd: make kill