---
- hosts: app_host
  remote_user: root
  tasks:
    - name: Run Local Benchmark
      shell:
        chdir: '/root/puma-performance-sketch/'
        cmd: make benchmark
      environment:
        RACK_INSTURMENT: "{{ lookup('env', 'RACK_INSTURMENT') }}"
        WRK_CONCURRENT: "{{ lookup('env', 'WRK_CONCURRENT') }}"
        PUMA_STATSD: "{{ lookup('env', 'PUMA_STATSD') }}"

      register: benchmark

    - name: Show benchmark output
      debug:
        msg: "{{ benchmark.stdout }}"

    - name: Save output
      local_action:
        module: copy
        content: "{{ benchmark.stdout }}"
        dest: "../wrk_benchmark.{{ ansible_date_time.iso8601_basic }}.txt"