---
- hosts: app_host
  remote_user: root
  tasks:
    - name: Run Local Benchmark
      shell:
        chdir: '/root/puma-performance-sketch/'
        cmd: make benchmark
      environment:
        RACK_INSTURMENT: "{{ lookup('env', 'RACK_INSTURMENT') | default('true', true) }}"
        WRK_CONCURRENT: "{{ lookup('env', 'WRK_CONCURRENT') | default('4', true)  }}"
        PUMA_STATSD: "{{ lookup('env', 'PUMA_STATSD') | default('false', true) }}"
        DURATION: "{{ lookup('env', 'DURATION') | default('30', true)  }}"

      register: benchmark

    - name: Show benchmark output
      debug:
        msg: "{{ benchmark.stdout }}"

    - name: Save output
      local_action:
        module: copy
        content: "{{ benchmark.stdout }}"
        dest: "../results/wrk_benchmark.{{ ansible_date_time.iso8601_basic }}.txt"